name: Build and Release Windows Executable

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller matplotlib pandas

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload artifact for debugging (optional)
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/*.exe

      - name: Create GitHub Release and upload executable
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
